# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "English"
weight = 1

[pt-br]
languageName = "Portuguese"
languagedirection = "ltr"
title = "Portuguese"
weight = 2
