# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Request.do - A ServiceNow Blog"
weight = 1

[pt-br]
languageName = "Portuguese"
languagedirection = "ltr"
title = "Request.do - A ServiceNow Blog"
weight = 2
