# Configure main menu and social menu

[[main]]
identifier = "home"
name = "Home"
url = "/"

[main.params]
icon = "home"
newtab = false

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/mvkassak/"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "Linkedin"
url = "https://linkedin.com/in/mvkassak/"

[social.params]
icon = "brand-linkedin"
